#!/bin/bash

# Author: Edward Speer
# Date Created: 1/7/2023
# Last Modeified: 1/7/2023

# Description:
# This script simply created tar compressed backup files of my home directory

# Usage:
# Run the script from home directory and it will produce a .tar backup of your 
# home directory which will be created in your home directory

tar -cvf ~/bash_course/my_backup_"$(date +%d-%m-%Y_%H-%M-%S)".tar ~/* 2>/dev/null
exit 0

